export { Dashboard } from './Dashboard'
export { POS } from './POS'
export { Menu } from './Menu'
export { Kitchen } from './Kitchen'
export { Inventory } from './Inventory'
export { Alerts } from './Alerts'
export { Settings } from './Settings'
export { Login } from './Login'
export { default as Home } from './Home'
export { default as CameraView } from './CameraView'
