name: Hata bildirimi
description: Bulduğunuz problemi raporlayın
labels: [bug]
body:
  - type: input
    id: summary
    attributes:
      label: Özet
      description: Kısa ve net
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Tekrarlama adımları
      description: 1) ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Beklenen davranış
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Ekran görüntüsü / Log
      description: Opsiyonel
  - type: input
    id: env
    attributes:
      label: Ortam bilgisi
      description: örn. branch, tarayıcı, cihaz, API versiyonu
