name: Özellik isteği
description: Yeni bir özellik ya da geliştirme önerin
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Başlık
      description: Kısa özet
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Hangi ihtiyacı çözüyor?
  - type: textarea
    id: proposal
    attributes:
      label: Çözüm
      description: Nasıl çalışmalı?
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Ek notlar
      description: Tasarım linkleri, API gereksinimleri
