entrance_line:
  start: [0.05, 0.95]
  end: [0.95, 0.95]
  inside_on: top

queue_zone:
  id: queue
  polygon:
    - [0.35, 0.55]
    - [0.65, 0.55]
    - [0.65, 0.95]
    - [0.35, 0.95]

tables:
  - id: table-1
    name: Window Booth
    polygon:
      - [0.05, 0.1]
      - [0.28, 0.1]
      - [0.28, 0.35]
      - [0.05, 0.35]
  - id: table-2
    name: Middle High-top
    polygon:
      - [0.36, 0.1]
      - [0.64, 0.1]
      - [0.64, 0.35]
      - [0.36, 0.35]
  - id: table-3
    name: Quiet Corner
    polygon:
      - [0.72, 0.1]
      - [0.95, 0.1]
      - [0.95, 0.35]
      - [0.72, 0.35]

heatmap:
  grid_width: 6
  grid_height: 4

alert_thresholds:
  queue_long_wait: 180.0 # seconds (3 minutes)
  queue_high_count: 8 # number of people
  crowd_surge_threshold: 5 # sudden increase in people count
  crowd_surge_window: 30.0 # seconds to detect surge
  table_long_stay: 7200.0 # seconds (2 hours)
